config_version = 1

[chat]
    # should the chat messages be echoed to velocity's console?
    log_to_console = true

    # should chat messages be passed through to the minecraft server?
    # it will show duplicate messages in the senders chat
    passthrough = false

    # should chat messages be parsed through minimessage?
    # player will be able to use styles such as <rainbow>hello</rainbow> in their messages
    parse_player_messages = false

    # when a player connects to velocity
    msg_join = "<gold><player> connected</gold>"

    # when a player disconnects from velocity
    msg_quit = "<gold><player> disconnected</gold>"

    # when a player speaks
    msg_chat = "<player>: <message>"
